





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;



namespace HKRS.Project.Website.GlassMapper.Models
{

	public partial interface IGlassBase{
		
		[SitecoreId]
		Guid Id{ get; }

		[SitecoreInfo(SitecoreInfoType.Language)]
        Language Language{ get; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        int Version { get; }

	}

	public abstract partial class GlassBase : IGlassBase{
		
		[SitecoreId]
		public virtual Guid Id{ get; private set;}

		[SitecoreInfo(SitecoreInfoType.Language)]
        public virtual Language Language{ get; private set; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        public virtual int Version { get; private set; }


	}
}
namespace HKRS.Project.Website.GlassMapper.Models.sitecore.templates.User_Defined.Feature.BasicContent
{


 	/// <summary>
	/// IBasicContent Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Feature/BasicContent/BasicContent</para>	
	/// <para>ID: 5a2af81f-a7c1-44c0-9a35-c087377c3bd1</para>	
	/// </summary>
	[SitecoreType(TemplateId=IBasicContentConstants.TemplateIdString )] //, Cachable = true
	public partial interface IBasicContent : IGlassBase 
	{
								/// <summary>
					/// The Body field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: ebf8a884-aa0c-4663-9e92-ccaee290cf49</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IBasicContentConstants.BodyFieldName)]
					string Body  {get; set;}
			
								/// <summary>
					/// The Image field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: a5c1cd50-8203-42f8-b9a4-86b9102faaf2</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IBasicContentConstants.ImageFieldName)]
					Image Image  {get; set;}
			
								/// <summary>
					/// The Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 2ae9779d-6aca-41c8-bc0f-a3ce4421ea74</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IBasicContentConstants.TitleFieldName)]
					string Title  {get; set;}
			
				}


	public static partial class IBasicContentConstants{

			public const string TemplateIdString = "5a2af81f-a7c1-44c0-9a35-c087377c3bd1";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "BasicContent";

					
			public static readonly ID BodyFieldId = new ID("ebf8a884-aa0c-4663-9e92-ccaee290cf49");
			public const string BodyFieldName = "Body";
			
					
			public static readonly ID ImageFieldId = new ID("a5c1cd50-8203-42f8-b9a4-86b9102faaf2");
			public const string ImageFieldName = "Image";
			
					
			public static readonly ID TitleFieldId = new ID("2ae9779d-6aca-41c8-bc0f-a3ce4421ea74");
			public const string TitleFieldName = "Title";
			
			

	}

	
	/// <summary>
	/// BasicContent
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/Feature/BasicContent/BasicContent</para>	
	/// <para>ID: 5a2af81f-a7c1-44c0-9a35-c087377c3bd1</para>	
	/// </summary>
	[SitecoreType(TemplateId=IBasicContentConstants.TemplateIdString)] //, Cachable = true
	public partial class BasicContent  : GlassBase, IBasicContent 
	{
	   
						/// <summary>
				/// The Body field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: ebf8a884-aa0c-4663-9e92-ccaee290cf49</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBasicContentConstants.BodyFieldName)]
				public virtual string Body  {get; set;}
					
						/// <summary>
				/// The Image field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: a5c1cd50-8203-42f8-b9a4-86b9102faaf2</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBasicContentConstants.ImageFieldName)]
				public virtual Image Image  {get; set;}
					
						/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 2ae9779d-6aca-41c8-bc0f-a3ce4421ea74</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBasicContentConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
			
	}
}
