





#pragma warning disable 1591
#pragma warning disable 0108
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Team Development for Sitecore.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;   
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;



namespace HKRS.Common.Models.AutoGen
{

	public partial interface IGlassBase{
		
		[SitecoreId]
		Guid Id{ get; }

		[SitecoreInfo(SitecoreInfoType.Language)]
        Language Language{ get; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        int Version { get; }

	}

	public abstract partial class GlassBase : IGlassBase{
		
		[SitecoreId]
		public virtual Guid Id{ get; private set;}

		[SitecoreInfo(SitecoreInfoType.Language)]
        public virtual Language Language{ get; private set; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        public virtual int Version { get; private set; }


	}
}
namespace HKRS.Common.Models.AutoGen.sitecore.templates.User_Defined.HKRS.Foundation.Common
{


 	/// <summary>
	/// INavigation_Link Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/HKRS/Foundation/Common/Navigation Link</para>	
	/// <para>ID: 03162890-1653-467d-bb08-83e15eeb5e95</para>	
	/// </summary>
	[SitecoreType(TemplateId=INavigation_LinkConstants.TemplateIdString )] //, Cachable = true
	public partial interface INavigation_Link : IGlassBase 
	{
								/// <summary>
					/// The Link Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 77d1277c-cb9c-430c-a61a-396878a4b562</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(INavigation_LinkConstants.Link_TitleFieldName)]
					string Link_Title  {get; set;}
			
								/// <summary>
					/// The Link field.
					/// <para></para>
					/// <para>Field Type: General Link</para>		
					/// <para>Field ID: 74ba639a-958f-4d9d-a566-0d8002ccaf21</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(INavigation_LinkConstants.LinkFieldName)]
					Link Link  {get; set;}
			
				}


	public static partial class INavigation_LinkConstants{

			public const string TemplateIdString = "03162890-1653-467d-bb08-83e15eeb5e95";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Navigation Link";

					
			public static readonly ID Link_TitleFieldId = new ID("77d1277c-cb9c-430c-a61a-396878a4b562");
			public const string Link_TitleFieldName = "Link Title";
			
					
			public static readonly ID LinkFieldId = new ID("74ba639a-958f-4d9d-a566-0d8002ccaf21");
			public const string LinkFieldName = "Link";
			
			

	}

	
	/// <summary>
	/// Navigation_Link
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/HKRS/Foundation/Common/Navigation Link</para>	
	/// <para>ID: 03162890-1653-467d-bb08-83e15eeb5e95</para>	
	/// </summary>
	[SitecoreType(TemplateId=INavigation_LinkConstants.TemplateIdString)] //, Cachable = true
	public partial class Navigation_Link  : GlassBase, INavigation_Link 
	{
	   
						/// <summary>
				/// The Link Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 77d1277c-cb9c-430c-a61a-396878a4b562</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(INavigation_LinkConstants.Link_TitleFieldName)]
				public virtual string Link_Title  {get; set;}
					
						/// <summary>
				/// The Link field.
				/// <para></para>
				/// <para>Field Type: General Link</para>		
				/// <para>Field ID: 74ba639a-958f-4d9d-a566-0d8002ccaf21</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(INavigation_LinkConstants.LinkFieldName)]
				public virtual Link Link  {get; set;}
					
			
	}
}
namespace HKRS.Common.Models.AutoGen.sitecore.templates.User_Defined.HKRS.Foundation.Hierarchy
{


 	/// <summary>
	/// IData_Folder Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/HKRS/Foundation/Hierarchy/Data Folder</para>	
	/// <para>ID: 0c7f402e-f67a-4d39-a7cb-d99ecd22ed4e</para>	
	/// </summary>
	[SitecoreType(TemplateId=IData_FolderConstants.TemplateIdString )] //, Cachable = true
	public partial interface IData_Folder : IGlassBase 
	{
				}


	public static partial class IData_FolderConstants{

			public const string TemplateIdString = "0c7f402e-f67a-4d39-a7cb-d99ecd22ed4e";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Data Folder";

			

	}

	
	/// <summary>
	/// Data_Folder
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/HKRS/Foundation/Hierarchy/Data Folder</para>	
	/// <para>ID: 0c7f402e-f67a-4d39-a7cb-d99ecd22ed4e</para>	
	/// </summary>
	[SitecoreType(TemplateId=IData_FolderConstants.TemplateIdString)] //, Cachable = true
	public partial class Data_Folder  : GlassBase, IData_Folder 
	{
	   
			
	}
}
namespace HKRS.Common.Models.AutoGen.sitecore.templates.User_Defined.HKRS.Foundation.Hierarchy
{


 	/// <summary>
	/// IComponents_Folder Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/HKRS/Foundation/Hierarchy/Components Folder</para>	
	/// <para>ID: 3d8dc175-80c5-4c0e-b2de-9723d17a8fb4</para>	
	/// </summary>
	[SitecoreType(TemplateId=IComponents_FolderConstants.TemplateIdString )] //, Cachable = true
	public partial interface IComponents_Folder : IGlassBase 
	{
				}


	public static partial class IComponents_FolderConstants{

			public const string TemplateIdString = "3d8dc175-80c5-4c0e-b2de-9723d17a8fb4";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Components Folder";

			

	}

	
	/// <summary>
	/// Components_Folder
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/HKRS/Foundation/Hierarchy/Components Folder</para>	
	/// <para>ID: 3d8dc175-80c5-4c0e-b2de-9723d17a8fb4</para>	
	/// </summary>
	[SitecoreType(TemplateId=IComponents_FolderConstants.TemplateIdString)] //, Cachable = true
	public partial class Components_Folder  : GlassBase, IComponents_Folder 
	{
	   
			
	}
}
namespace HKRS.Common.Models.AutoGen.sitecore.templates.User_Defined.HKRS.Feature
{


 	/// <summary>
	/// ISiteHeader Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/HKRS/Feature/SiteHeader</para>	
	/// <para>ID: 46669a0f-f23f-47b6-a905-ef6266d971a4</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISiteHeaderConstants.TemplateIdString )] //, Cachable = true
	public partial interface ISiteHeader : IGlassBase 
	{
								/// <summary>
					/// The Description field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: 12d27330-d3ee-452e-b791-c48caf6f076d</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISiteHeaderConstants.DescriptionFieldName)]
					string Description  {get; set;}
			
								/// <summary>
					/// The Header Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 308ed6e9-6647-49cd-ab17-a6d2aa73a3d1</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISiteHeaderConstants.Header_TitleFieldName)]
					string Header_Title  {get; set;}
			
								/// <summary>
					/// The Logo field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: 23123408-8ffc-486a-8641-42d4b1d6a7ce</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISiteHeaderConstants.LogoFieldName)]
					Image Logo  {get; set;}
			
				}


	public static partial class ISiteHeaderConstants{

			public const string TemplateIdString = "46669a0f-f23f-47b6-a905-ef6266d971a4";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "SiteHeader";

					
			public static readonly ID DescriptionFieldId = new ID("12d27330-d3ee-452e-b791-c48caf6f076d");
			public const string DescriptionFieldName = "Description";
			
					
			public static readonly ID Header_TitleFieldId = new ID("308ed6e9-6647-49cd-ab17-a6d2aa73a3d1");
			public const string Header_TitleFieldName = "Header Title";
			
					
			public static readonly ID LogoFieldId = new ID("23123408-8ffc-486a-8641-42d4b1d6a7ce");
			public const string LogoFieldName = "Logo";
			
			

	}

	
	/// <summary>
	/// SiteHeader
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/HKRS/Feature/SiteHeader</para>	
	/// <para>ID: 46669a0f-f23f-47b6-a905-ef6266d971a4</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISiteHeaderConstants.TemplateIdString)] //, Cachable = true
	public partial class SiteHeader  : GlassBase, ISiteHeader 
	{
	   
						/// <summary>
				/// The Description field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: 12d27330-d3ee-452e-b791-c48caf6f076d</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteHeaderConstants.DescriptionFieldName)]
				public virtual string Description  {get; set;}
					
						/// <summary>
				/// The Header Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 308ed6e9-6647-49cd-ab17-a6d2aa73a3d1</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteHeaderConstants.Header_TitleFieldName)]
				public virtual string Header_Title  {get; set;}
					
						/// <summary>
				/// The Logo field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: 23123408-8ffc-486a-8641-42d4b1d6a7ce</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteHeaderConstants.LogoFieldName)]
				public virtual Image Logo  {get; set;}
					
			
	}
}
namespace HKRS.Common.Models.AutoGen.sitecore.templates.User_Defined.HKRS.Feature.BasicContent
{


 	/// <summary>
	/// IBasicContent Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/HKRS/Feature/BasicContent/BasicContent</para>	
	/// <para>ID: 5a2af81f-a7c1-44c0-9a35-c087377c3bd1</para>	
	/// </summary>
	[SitecoreType(TemplateId=IBasicContentConstants.TemplateIdString )] //, Cachable = true
	public partial interface IBasicContent : IGlassBase 
	{
								/// <summary>
					/// The Body field.
					/// <para></para>
					/// <para>Field Type: Rich Text</para>		
					/// <para>Field ID: ebf8a884-aa0c-4663-9e92-ccaee290cf49</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IBasicContentConstants.BodyFieldName)]
					string Body  {get; set;}
			
								/// <summary>
					/// The Image field.
					/// <para></para>
					/// <para>Field Type: Image</para>		
					/// <para>Field ID: a5c1cd50-8203-42f8-b9a4-86b9102faaf2</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IBasicContentConstants.ImageFieldName)]
					Image Image  {get; set;}
			
								/// <summary>
					/// The Title field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 2ae9779d-6aca-41c8-bc0f-a3ce4421ea74</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(IBasicContentConstants.TitleFieldName)]
					string Title  {get; set;}
			
				}


	public static partial class IBasicContentConstants{

			public const string TemplateIdString = "5a2af81f-a7c1-44c0-9a35-c087377c3bd1";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "BasicContent";

					
			public static readonly ID BodyFieldId = new ID("ebf8a884-aa0c-4663-9e92-ccaee290cf49");
			public const string BodyFieldName = "Body";
			
					
			public static readonly ID ImageFieldId = new ID("a5c1cd50-8203-42f8-b9a4-86b9102faaf2");
			public const string ImageFieldName = "Image";
			
					
			public static readonly ID TitleFieldId = new ID("2ae9779d-6aca-41c8-bc0f-a3ce4421ea74");
			public const string TitleFieldName = "Title";
			
			

	}

	
	/// <summary>
	/// BasicContent
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/HKRS/Feature/BasicContent/BasicContent</para>	
	/// <para>ID: 5a2af81f-a7c1-44c0-9a35-c087377c3bd1</para>	
	/// </summary>
	[SitecoreType(TemplateId=IBasicContentConstants.TemplateIdString)] //, Cachable = true
	public partial class BasicContent  : GlassBase, IBasicContent 
	{
	   
						/// <summary>
				/// The Body field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// <para>Field ID: ebf8a884-aa0c-4663-9e92-ccaee290cf49</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBasicContentConstants.BodyFieldName)]
				public virtual string Body  {get; set;}
					
						/// <summary>
				/// The Image field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// <para>Field ID: a5c1cd50-8203-42f8-b9a4-86b9102faaf2</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBasicContentConstants.ImageFieldName)]
				public virtual Image Image  {get; set;}
					
						/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 2ae9779d-6aca-41c8-bc0f-a3ce4421ea74</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(IBasicContentConstants.TitleFieldName)]
				public virtual string Title  {get; set;}
					
			
	}
}
namespace HKRS.Common.Models.AutoGen.sitecore.templates.User_Defined.HKRS.Feature
{


 	/// <summary>
	/// ISiteFooter Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/HKRS/Feature/SiteFooter</para>	
	/// <para>ID: a009e83e-ffd4-494e-a861-e80836bc8bb4</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISiteFooterConstants.TemplateIdString )] //, Cachable = true
	public partial interface ISiteFooter : IGlassBase 
	{
								/// <summary>
					/// The Bottom Footer Links field.
					/// <para></para>
					/// <para>Field Type: TreelistEx</para>		
					/// <para>Field ID: 653649cc-aaad-4636-bf2a-0b0a5a9dd7d9</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISiteFooterConstants.Bottom_Footer_LinksFieldName)]
					IEnumerable<Guid> Bottom_Footer_Links  {get; set;}
			
								/// <summary>
					/// The Contact Us Text field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 559a60b9-a102-46f4-ba78-dcee2b82ec3a</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISiteFooterConstants.Contact_Us_TextFieldName)]
					string Contact_Us_Text  {get; set;}
			
								/// <summary>
					/// The Copyright Text field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 71a547ce-dcf7-4551-a003-9b9c14d91b0b</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISiteFooterConstants.Copyright_TextFieldName)]
					string Copyright_Text  {get; set;}
			
								/// <summary>
					/// The Phone Number field.
					/// <para></para>
					/// <para>Field Type: Single-Line Text</para>		
					/// <para>Field ID: 944d8199-178c-4583-a1a2-f5c39a315abc</para>
					/// <para>Custom Data: </para>
					/// </summary>
					[SitecoreField(ISiteFooterConstants.Phone_NumberFieldName)]
					string Phone_Number  {get; set;}
			
				}


	public static partial class ISiteFooterConstants{

			public const string TemplateIdString = "a009e83e-ffd4-494e-a861-e80836bc8bb4";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "SiteFooter";

					
			public static readonly ID Bottom_Footer_LinksFieldId = new ID("653649cc-aaad-4636-bf2a-0b0a5a9dd7d9");
			public const string Bottom_Footer_LinksFieldName = "Bottom Footer Links";
			
					
			public static readonly ID Contact_Us_TextFieldId = new ID("559a60b9-a102-46f4-ba78-dcee2b82ec3a");
			public const string Contact_Us_TextFieldName = "Contact Us Text";
			
					
			public static readonly ID Copyright_TextFieldId = new ID("71a547ce-dcf7-4551-a003-9b9c14d91b0b");
			public const string Copyright_TextFieldName = "Copyright Text";
			
					
			public static readonly ID Phone_NumberFieldId = new ID("944d8199-178c-4583-a1a2-f5c39a315abc");
			public const string Phone_NumberFieldName = "Phone Number";
			
			

	}

	
	/// <summary>
	/// SiteFooter
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/HKRS/Feature/SiteFooter</para>	
	/// <para>ID: a009e83e-ffd4-494e-a861-e80836bc8bb4</para>	
	/// </summary>
	[SitecoreType(TemplateId=ISiteFooterConstants.TemplateIdString)] //, Cachable = true
	public partial class SiteFooter  : GlassBase, ISiteFooter 
	{
	   
						/// <summary>
				/// The Bottom Footer Links field.
				/// <para></para>
				/// <para>Field Type: TreelistEx</para>		
				/// <para>Field ID: 653649cc-aaad-4636-bf2a-0b0a5a9dd7d9</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteFooterConstants.Bottom_Footer_LinksFieldName)]
				public virtual IEnumerable<Guid> Bottom_Footer_Links  {get; set;}
					
						/// <summary>
				/// The Contact Us Text field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 559a60b9-a102-46f4-ba78-dcee2b82ec3a</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteFooterConstants.Contact_Us_TextFieldName)]
				public virtual string Contact_Us_Text  {get; set;}
					
						/// <summary>
				/// The Copyright Text field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 71a547ce-dcf7-4551-a003-9b9c14d91b0b</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteFooterConstants.Copyright_TextFieldName)]
				public virtual string Copyright_Text  {get; set;}
					
						/// <summary>
				/// The Phone Number field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// <para>Field ID: 944d8199-178c-4583-a1a2-f5c39a315abc</para>
				/// <para>Custom Data: </para>
				/// </summary>
				[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Team Development for Sitecore - GlassItem.tt", "1.0")]
				[SitecoreField(ISiteFooterConstants.Phone_NumberFieldName)]
				public virtual string Phone_Number  {get; set;}
					
			
	}
}
namespace HKRS.Common.Models.AutoGen.sitecore.templates.User_Defined.HKRS.Foundation.Common
{


 	/// <summary>
	/// INavigation_Link_Folder Interface
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/HKRS/Foundation/Common/Navigation Link Folder</para>	
	/// <para>ID: f930298a-3b7a-4dea-9389-16648894212c</para>	
	/// </summary>
	[SitecoreType(TemplateId=INavigation_Link_FolderConstants.TemplateIdString )] //, Cachable = true
	public partial interface INavigation_Link_Folder : IGlassBase 
	{
				}


	public static partial class INavigation_Link_FolderConstants{

			public const string TemplateIdString = "f930298a-3b7a-4dea-9389-16648894212c";
			public static readonly ID TemplateId = new ID(TemplateIdString);
			public const string TemplateName = "Navigation Link Folder";

			

	}

	
	/// <summary>
	/// Navigation_Link_Folder
	/// <para></para>
	/// <para>Path: /sitecore/templates/User Defined/HKRS/Foundation/Common/Navigation Link Folder</para>	
	/// <para>ID: f930298a-3b7a-4dea-9389-16648894212c</para>	
	/// </summary>
	[SitecoreType(TemplateId=INavigation_Link_FolderConstants.TemplateIdString)] //, Cachable = true
	public partial class Navigation_Link_Folder  : GlassBase, INavigation_Link_Folder 
	{
	   
			
	}
}
